<?php

namespace Database\Seeders;

use App\Models\About;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AboutSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        About::create([
            'title' => [
                'en' => 'About Us',
                'ru' => 'О нас',
                'hy' => 'Մեր մասին',
            ],

            'description' => [
                'en' => "The SanTech brand is represented by «Lid Mech LLC», a company specializing in the import and distribution of air conditioning, heating, cooling, ventilation, water supply, drainage, smoke extraction, and fire protection systems.Today, «Lid Mech LLC»,  operates on an area of approximately 20,000 square meters. The company is supported by a skilled and experienced team whose extensive knowledge and professional expertise are dedicated to importing high-quality engineering systems, providing professional consultation, delivering excellent sales service, and ensuring customer and partner satisfaction.The company offers a wide range of products that have established a strong position in the market over the years, based on quality, innovation, and reliability.«Lid Mech LLC», collaborates with hundreds of internationally recognized manufacturers. Since 2011, the company has been the largest importer of  GREE and AERMEC brands in Armenia. Since 2009, it has been importing BAENNINGER, a globally recognized manufacturer of premium polyethylene piping systems, and serves as the brand's exclusive representative in the Republic of Armenia.The company also cooperates with many other leading international manufacturers, including the Italian brands EBARA, ECOFLAME, ALDES, TIEMME, ARISTON, FIORINI, the German brands TESTO, JUERGEN SCHLOSSER, OSTENDORF, K-FLEX, as well as several other European companies such as HERZ, Dantherm, Tecoffi, BOKI, SPIROTECH, KOSPEL. Among its Russian partners are VKT, VEZA, IZOLPROEKT, INTER-SPRINKLER, ROVEN, and TEPLOVODOOKHRAN/PULSAR.The company's history dates back to 1956, when it was established as the installation department of the Special Santekhmontazh OJSC, specializing in plumbing and sanitary installation works.In 1999, the company was privatized and reorganized into Special Santekhmontazh OJSC under the leadership of Director Meruzhan Rafayelyan.In August 2004, the organization was reorganized into a CJSC.The mission of «Lid Mech LLC» is to improve people's comfort and safety through the expertise of its highly qualified professionals by providing advanced engineering solutions for residential, commercial, healthcare, administrative, and industrial buildings.Decades of experience enable the company to deliver the best solutions to its customers and partners. Throughout the years «Lid Mech LLC» has built a strong reputation in the market based on quality, innovation, and trust.",

                'ru' => 'Бренд SanTech представляет компания ООО «Лид Меч», специализирующаяся на импорте и продаже систем кондиционирования, отопления, охлаждения, вентиляции, водоснабжения, водоотведения, дымоудаления и противопожарной защиты.Сегодня ООО «Лид Меч» располагает территорией площадью около 20 000 кв. м. В компании работает команда квалифицированных и опытных специалистов, чей многолетний опыт и профессионализм направлены на поставку высококачественных инженерных систем и оборудования, предоставление профессиональных консультаций, качественное обслуживание клиентов и удовлетворение потребностей партнеров.Компания предлагает широкий ассортимент продукции, которая за многие годы укрепила свои позиции на рынке Армении благодаря высокому качеству, инновациям и надежности.ООО «Лид Меч» сотрудничает с сотнями известных международных производителей. С 2011 года компания является крупнейшим импортером брендов GREE и AERMEC в Армении. С 2009 года компания импортирует продукцию бренда BÄNNINGER, признанного одним из лучших мировых производителей полиэтиленовых труб, и является его эксклюзивным представителем на территории Республики Армения.Компания также сотрудничает с рядом других авторитетных производителей, среди которых итальянские компании EBARA, ECOFLAME, ALDES, TIEMME, ARISTON, FIORINI, немецкие TESTO, JUERGEN SCHLOSSER, OSTENDORF, K-FLEX, а также европейские компании HERZ, Dantherm, Tecoffi, BOKI, SPIROTECH, KOSPEL. Среди российских партнеров компании — VKT, VEZA, ИЗОЛПРОЕКТ, ИНТЕР-СПРИНКЛЕР, РОВЕН и ТЕПЛОВОДОХРАН/ПУЛЬСАР.История компании начинается с 1956 года, когда она была основана как монтажное управление треста «Армсантехмонтаж», выполнявшего сантехнические и монтажные работы.В 1999 году предприятие было приватизировано и преобразовано в Открытое акционерное общество «Спец. Сантехмонтаж» под руководством директора Меружана Рафаеляна.В августе 2004 года организация была преобразована в закрытое акционерное общество.Основная цель ООО «Лид Меч» — благодаря высококвалифицированным специалистам обеспечивать людям комфорт и безопасность в жилых домах, административных зданиях, медицинских учреждениях, производственных объектах и на рабочих местах, предлагая современные инженерные решения.Многолетний опыт позволяет компании предлагать своим клиентам и партнерам наиболее эффективные и надежные решения. За десятилетия работы ООО «Лид Меч» заслужило прочную репутацию на рынке, основанную на качестве, инновациях и доверии.',

                'hy' => 'SanTech ապրանքանիշը ներկայացնում է «Լիդ Մեչ» ՍՊ ընկերությունը, որ մասնագիտացած է օդորակման, ջեռուցման, հովացման, օդափոխության, ինչպես նաև ջրամատակարարման, ջրահեռացման, ծխահեռացման ու հակահրդեհային համակարգերի ներմուծմամբ և վաճառքով: «Լիդ Մեչ» ՍՊ ընկերությունն այսօր զբաղեցնում է մոտ 20000 քմ տարածք: Ունի հմուտ և փորձառու աշխատանքային թիմ, որոնց տարիների ընթացքում ձեռք բերած գիտելիքներն ու մասնագիտական հմտությունները ուղղված են բարձրակարգ համակարգերի և սարքավորումների ներմուծմանը, խորհրդատվությանը, վաճառքին, ինչպես նաև գոհացնում են հաճախորդներին և գործընկերներին:Ընկերությունն առաջարկում է լայն ապրանքատեսականի, որը տարիների ընթացքում հաստատել է իր դիրքը շուկայում՝ հիմնվելով որակի, նորարարության և վստահելիության վրա:«Լիդ Մեչ» ՍՊ ընկերությունը համագործակցում է հարյուրավոր հայտնի միջազգային կազմակերպությունների հետ: 2011 թվականից ի վեր հանդիսանում է GREE և AERMEC ապրանքանիշների խոշորագույն ներկրողը Հայաստանում: BAENNINGER ապրանքանիշը, որը միջազգային շուկայում ճանաչվել է պոլիէթիլենային հումքից արտադրված խողովակների լավագույն արտադրողը, «Լիդ Մեչ» ՍՊ» ընկերությունը սկսել է ներկրել 2009 թվականից և հանդիսանում է էքսկլյուզիվ ներկայացուցիչը ՀՀ-ում:«Լիդ Մեչ» ՍՊ ընկերությունը համագործակցում է ոլորտի մի շարք այլ հեղինակավոր կազմակերպությունների հետ ևս, ինչպիսին են, օրինակ, իտալական EBARA, ECOFLAME, ALDES, TIEMME, ARISTON, FIORINI, գերմանական TESTO, JUERGEN SCHLOSSER, OSTENDORF, K-FLEX. Մի շարք այլ եվրոպական ընկերությունների հետ, ինչպիսին են՝ HERZ, Dantherm, Tecoffi, BOKI, SPIROTECH, KOSPEL, ռուսական ընկերություններից են՝ VKT, VEZA, ИЗОЛПРОЕКТ, ИНТЕР-СПРИНКЛЕР, РОВЕН, ТЕПЛОВОДОХРАН/ПУЛЬСАР.«Լիդ Մեչ» ՍՊ ընկերությունն իր գործունեությունը սկսել է 1956 թվականին որպես «Հայ սանտեխմոնտաժ» տրեստի մոնտաժային վարչություն, որը զբաղվել է սանտեխնիկայի մոնտաժով:Հետագայում՝ 1999 թվականին, այն սեփականաշնորհվել է՝ դառնալով «Հատուկ սանտեխմոնտաժ» բաց բաժնետիրական ընկերություն՝ ի դեմս տնօրեն Մերուժան Ռաֆայելյանի:2004 թվականի օգոստոսին կազմակերպությունը դարձել է փակ բաժնետիրական ընկերություն:«Լիդ Մեչ» ՍՊ ընկերությունը նպատակն է իր բարձրակարգ մասնագետների շնորհիվ ապահովել մարդկանց հարմարավետ կյանքը և անվտանգությունը նրանց տներում և աշխատավայրերում, ադմինիստրատիվ, առողջապահական և արտադրական շինություններում: Մեր տասնամյակների փորձը թույլ է տալիս առաջարկել լավագույն լուծումները հաճախորդներին և գործընկերներին։ Այս տարիների ընթացքում հաստատել ենք մեր դիրքը շուկայում՝ հիմնվելով որակի, նորարարության և վստահելիության վրա:',
            ],
        ]);
    }
}
